---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vote-ui-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
