apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    argocd/app-selector: rht-gitops.com/janus-argocd=${{values.component_id}}-bootstrap
    backstage.io/kubernetes-id: ${{values.component_id}}
    janus-idp.io/tekton: ${{values.component_id}}
    backstage.io/source-location: url:https://${{values.host}}/${{values.destination}}
    backstage.io/techdocs-ref: url:https://${{values.host}}/${{values.destination}}
    gitlab.com/project-slug: ${{values.destination}}
  tags:
    - go
    - backend
  links:
    - url: https://console-openshift-console${{values.cluster}}/dev-pipelines/ns/${{values.namespace}}/
      title: Pipelines
      icon: web
    - url: https://devspaces${{values.cluster}}/#https://${{values.host}}/${{values.destination}}
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces${{values.cluster}}/#https://${{values.host}}/${{values.destination}}?che-editor=che-incubator/che-idea/latest
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
  system: vote-app-${{values.owner}}
  providesApis:
    - vote-api-${{values.owner}}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: vote-app-${{values.owner}}
  tags:
    - vote
    - python
    - go
    - openshift
spec:
  owner: ${{values.owner | dump}}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: vote-api-${{values.owner}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
spec:
  type: openapi
  lifecycle: production
  owner: ${{values.owner | dump}}
  system: vote-app-${{values.owner}}
  definition:
    $text: ./openapi.yaml

